# Generated by Django 5.2.13 on 2026-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
