# Generated by Django 5.2.13 on 2026-05-11 09:52

from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_address_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=apps.orders.models.generate_order_number,
                max_length=20,
                unique=True,
            ),
        ),
    ]
