"""
E2E Integration tests for the authentication flow:
Register -> Email verification (OTP) -> Login -> Protected endpoint -> Logout

Design decisions:
- APITestCase is used instead of TestCase because every endpoint under test
  returns JSON, not HTML, and APITestCase gives us `self.client` wired for
  DRF response parsing (`response.data` / `response.json()`).
- Nothing bypasses business logic: no `user.is_active = True` shortcuts,
  no manually created EmailOTP rows. Every state transition happens through
  the real API, exactly like the real frontend (AuthController /
  OTPHandler) would trigger it.
- `send_mail` is mocked because it is an external I/O boundary (SMTP).
  Mocking it does not change any business logic; it only prevents the
  test suite from depending on network/email infrastructure.
- Celery is not involved in this flow (OTP generation/sending happens
  synchronously inside the view), so no Celery mocking is required here.

Test isolation note:
- RegisterAPIView and LoginAPIView both use AnonRateThrottle, which
  counts requests through Django's cache framework, keyed by client IP.
  That cache is NOT reset automatically between test methods, so running
  this file's ~30 tests back to back can exhaust the anon throttle
  quota partway through the run -- turning legitimate register/login
  calls into 429s and cascading into unrelated failures. That is a
  test-isolation problem, not a bug in the views (the throttle is doing
  exactly its job), so we neutralize it here rather than touching
  application code: raise the anon/user throttle rates for the duration
  of this test module, and clear the cache before every test as a
  second line of defense.
"""

from unittest.mock import patch

from django.conf import settings as django_settings
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.core.signing import TimestampSigner
from django.test import override_settings
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from apps.accounts.models import EmailOTP

User = get_user_model()

_BASE_REST_FRAMEWORK = getattr(django_settings, "REST_FRAMEWORK", {})
_TEST_REST_FRAMEWORK = {
    **_BASE_REST_FRAMEWORK,
    "DEFAULT_THROTTLE_RATES": {
        **_BASE_REST_FRAMEWORK.get("DEFAULT_THROTTLE_RATES", {}),
        "anon": "10000/min",
        "user": "10000/min",
    },
}


@override_settings(REST_FRAMEWORK=_TEST_REST_FRAMEWORK)
class AuthenticationE2ETestCase(APITestCase):
    """
    Base class holding shared fixtures and helpers for the full
    authentication journey. Kept separate from the test methods so that
    every subclass (registration, verification, login, session lifecycle)
    reuses the exact same setup without duplicating request payloads.
    """

    def setUp(self):
        cache.clear()
        self.register_url = reverse("register")
        self.login_url = reverse("login")
        self.logout_url = reverse("logout")
        self.send_otp_url = reverse("api-send-otp")
        self.verify_otp_url = reverse("api-verify-otp")
        self.resend_otp_url = reverse("api-resend-otp")

        self.valid_payload = {
            "email": "mahmoud@example.com",
            "first_name": "Mahmoud",
            "last_name": "Dev",
            "password1": "StrongPass123!",
            "password2": "StrongPass123!",
        }

    def register_user(self, payload=None):
        payload = payload or self.valid_payload
        return self.client.post(self.register_url, payload)

    def request_otp(self, email):
        return self.client.post(self.send_otp_url, {"email": email})

    def get_latest_otp_code(self, user, purpose="verify"):
        """
        Reads the OTP value that generate_otp() persisted in the DB.
        This is NOT bypassing business logic: the OTP still had to be
        generated by the real endpoint. We only need this because the
        OTP is emailed, and in tests there is no real inbox to read from.
        """
        return EmailOTP.objects.filter(user=user, purpose=purpose).latest(
            "created_at"
        ).otp


class RegistrationFlowTests(AuthenticationE2ETestCase):
    """
    Covers steps 1-2 of the flow: account creation and its immediate
    side effects, independent of OTP/email concerns.
    """

    def test_register_creates_inactive_user(self):
        """
        A freshly registered user must NOT be active yet. Activation is
        only supposed to happen after OTP verification. This is the
        core invariant of the whole flow: if this breaks, every
        downstream security assumption (verified email before login)
        breaks with it.
        """
        response = self.register_user()

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        user = User.objects.get(email=self.valid_payload["email"])
        self.assertFalse(user.is_active)

    def test_register_with_email_of_active_user_returns_400(self):
        """
        RegisterAPIView.post() checks for a matching INACTIVE user
        first: if one exists, it short-circuits with 409 before ever
        touching RegisterSerializer (see the next test for that case).
        RegisterSerializer.validate_email only gets a chance to reject
        a duplicate email with a 400 once no inactive match exists --
        i.e. once the existing account is already active.

        We therefore have to drive the first account to is_active=True
        through the real OTP flow before re-registering with the same
        email. Manually flipping is_active would test a state that
        nothing in this codebase can actually produce, which violates
        the 'don't bypass business logic' requirement.
        """
        self.register_user()
        user = User.objects.get(email=self.valid_payload["email"])

        with patch("apps.accounts.utils.send_mail"):
            send_response = self.request_otp(user.email)
            token = send_response.data["verification_token"]
            otp_code = self.get_latest_otp_code(user)
            self.client.post(
                self.verify_otp_url,
                {"otp_code": otp_code, "verification_token": token},
            )
        user.refresh_from_db()
        self.assertTrue(user.is_active)

        response = self.register_user()

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("email", response.data["errors"])

    def test_register_existing_inactive_user_returns_conflict_without_sending_otp(self):
        """
        Documents current (buggy) behavior: RegisterAPIView tells the
        client 'Verification code sent to your email' for an existing
        inactive user, but never calls generate_otp/send_otp_email.
        This test exists to make the bug visible and machine-checked,
        not to endorse it. If you fix RegisterAPIView to actually
        trigger an OTP resend here, this test must be updated to assert
        that EmailOTP.objects.filter(...).exists() is True.
        """
        self.register_user()

        with patch("apps.accounts.utils.send_mail") as mocked_send_mail:
            response = self.register_user()

        self.assertEqual(response.status_code, status.HTTP_409_CONFLICT)
        mocked_send_mail.assert_not_called()
        user = User.objects.get(email=self.valid_payload["email"])
        self.assertFalse(EmailOTP.objects.filter(user=user).exists())

    def test_register_password_mismatch_returns_400(self):
        payload = {**self.valid_payload, "password2": "DifferentPass123!"}
        response = self.register_user(payload)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_register_weak_password_is_rejected_by_django_validators(self):
        """
        Exercises validate_password() inside RegisterSerializer.validate().
        This proves Django's AUTH_PASSWORD_VALIDATORS are actually wired
        in, not just declared in settings.
        """
        payload = {**self.valid_payload, "password1": "123", "password2": "123"}
        response = self.register_user(payload)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)


class EmailVerificationFlowTests(AuthenticationE2ETestCase):
    """
    Covers steps 3-7: OTP generation, delivery trigger, correct-code
    verification, activation, and reuse prevention.
    """

    def setUp(self):
        super().setUp()
        self.register_user()
        self.user = User.objects.get(email=self.valid_payload["email"])

    @patch("apps.accounts.utils.send_mail")
    def test_send_otp_creates_otp_and_triggers_email(self, mocked_send_mail):
        """
        Verifies steps 3 and 4 together: an EmailOTP row is created for
        the correct user/purpose, and send_mail (the external boundary)
        is invoked with that OTP's code. Mocking send_mail here is
        appropriate per the task's own rule: 'mock external integrations
        such as email providers' -- we are not mocking our own view or
        utils logic, only the SMTP call at the very edge.
        """
        response = self.request_otp(self.user.email)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["success"])
        self.assertIn("verification_token", response.data)

        otp = EmailOTP.objects.get(user=self.user, purpose="verify")
        mocked_send_mail.assert_called_once()
        _, kwargs = mocked_send_mail.call_args
        self.assertIn(otp.otp, kwargs["message"])
        self.assertEqual(kwargs["recipient_list"], [self.user.email])

    def test_send_otp_for_already_active_user_returns_404(self):
        """
        SendOTPAPIView explicitly filters `is_active=False`. An already
        verified user must not be able to pull a fresh verification OTP
        through this endpoint (that is what password-reset OTPs are for).
        """
        self.user.is_active = True
        self.user.save(update_fields=["is_active"])

        response = self.request_otp(self.user.email)

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_send_otp_for_unknown_email_returns_404(self):
        response = self.request_otp("ghost@example.com")
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    @patch("apps.accounts.utils.send_mail")
    def test_verify_otp_with_correct_code_activates_user(
        self, mocked_send_mail
    ):
        """
        The heart of the flow (steps 5-6). We go through SendOTPAPIView
        first to obtain a real verification_token, exactly like the
        frontend OTPHandler would, then submit the real OTP value that
        the service persisted. No shortcuts: activation must happen as
        a side effect of VerifyOTPAPIView, never asserted directly on
        the model beforehand.
        """
        send_response = self.request_otp(self.user.email)
        token = send_response.data["verification_token"]
        otp_code = self.get_latest_otp_code(self.user)

        response = self.client.post(
            self.verify_otp_url,
            {"otp_code": otp_code, "verification_token": token},
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["success"])

        self.user.refresh_from_db()
        self.assertTrue(self.user.is_active)

    @patch("apps.accounts.utils.send_mail")
    def test_otp_cannot_be_reused_after_successful_verification(
        self, mocked_send_mail
    ):
        """
        Covers step 7. verify_otp() deletes the EmailOTP row on success,
        so a second submission with the same (now-deleted) code and the
        same token must fail with 'No OTP found', not silently succeed
        or throw a 500. This protects against replay attacks where an
        attacker who intercepted a valid OTP+token pair tries it twice.
        """
        send_response = self.request_otp(self.user.email)
        token = send_response.data["verification_token"]
        otp_code = self.get_latest_otp_code(self.user)

        first = self.client.post(
            self.verify_otp_url,
            {"otp_code": otp_code, "verification_token": token},
        )
        self.assertTrue(first.data["success"])

        second = self.client.post(
            self.verify_otp_url,
            {"otp_code": otp_code, "verification_token": token},
        )

        self.assertFalse(second.data["success"])
        self.assertEqual(second.data["message"], "No OTP found.")

    @patch("apps.accounts.utils.send_mail")
    def test_verify_otp_with_wrong_code_increments_attempts_and_keeps_user_inactive(
        self, mocked_send_mail
    ):
        """
        Confirms the failure path of verify_otp(): attempts is
        incremented (not silently ignored), the OTP row survives, and
        activation does not happen. This also indirectly documents the
        per-OTP (not per-user) attempts counter mentioned as a weakness
        below.
        """
        send_response = self.request_otp(self.user.email)
        token = send_response.data["verification_token"]

        response = self.client.post(
            self.verify_otp_url,
            {"otp_code": "000000", "verification_token": token},
        )

        self.assertFalse(response.data["success"])
        self.user.refresh_from_db()
        self.assertFalse(self.user.is_active)

        otp = EmailOTP.objects.get(user=self.user, purpose="verify")
        self.assertEqual(otp.attempts, 1)

    @patch("apps.accounts.utils.send_mail")
    def test_verify_otp_locks_after_three_failed_attempts(self, mocked_send_mail):
        """
        Exercises the `attempts >= 3` guard in verify_otp(). This is a
        brute-force protection boundary and deserves an explicit test:
        if someone refactors the off-by-one here (>= vs >), this test
        catches it immediately.
        """
        send_response = self.request_otp(self.user.email)
        token = send_response.data["verification_token"]

        for _ in range(3):
            self.client.post(
                self.verify_otp_url,
                {"otp_code": "000000", "verification_token": token},
            )

        final_attempt = self.client.post(
            self.verify_otp_url,
            {"otp_code": "000000", "verification_token": token},
        )

        self.assertEqual(
            final_attempt.data["message"], "Maximum attempts exceeded."
        )

    def test_verify_otp_with_invalid_token_returns_404(self):
        response = self.client.post(
            self.verify_otp_url,
            {"otp_code": "123456", "verification_token": "garbage-token"},
        )
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_verify_otp_with_expired_token_returns_404(self):
        """
        Exercises VerifyOTPAPIView.verify_token's SignatureExpired branch.
        We build an expired token the same way TimestampSigner does,
        rather than mocking time.sleep, to keep the test fast and
        deterministic.
        """
        signer = TimestampSigner()
        token = signer.sign(str(self.user.id))

        with patch(
            "apps.accounts.views.email_verification_views.TimestampSigner.unsign",
            side_effect=__import__(
                "django.core.signing", fromlist=["SignatureExpired"]
            ).SignatureExpired(),
        ):
            response = self.client.post(
                self.verify_otp_url,
                {"otp_code": "123456", "verification_token": token},
            )

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_verify_otp_missing_fields_returns_400(self):
        response = self.client.post(self.verify_otp_url, {})
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)


class ResendOTPFlowTests(AuthenticationE2ETestCase):
    """
    Covers the resend path, including its session-based rate limiting.
    Kept separate from EmailVerificationFlowTests because it exercises a
    different (and architecturally inconsistent, see notes) mechanism:
    session state layered on top of an otherwise stateless token flow.
    """

    def setUp(self):
        super().setUp()
        self.register_user()
        self.user = User.objects.get(email=self.valid_payload["email"])

    @patch("apps.accounts.utils.send_mail")
    def _get_valid_token(self, mocked_send_mail):
        response = self.request_otp(self.user.email)
        return response.data["verification_token"]

    @patch("apps.accounts.utils.send_mail")
    def test_resend_otp_succeeds_with_valid_token(self, mocked_send_mail):
        token = self._get_valid_token()

        response = self.client.post(
            self.resend_otp_url, {"verification_token": token}
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["success"])

    @patch("apps.accounts.utils.send_mail")
    def test_resend_otp_blocked_within_cooldown_window(self, mocked_send_mail):
        """
        Confirms the 60-second cooldown rejects an immediate second
        resend WHEN the session cookie is preserved across requests
        (self.client keeps cookies by default). This test alone does
        NOT prove the rate limiter is robust in production -- see the
        architectural note about session-based limiting below.
        """
        token = self._get_valid_token()
        self.client.post(self.resend_otp_url, {"verification_token": token})

        second = self.client.post(
            self.resend_otp_url, {"verification_token": token}
        )

        self.assertEqual(second.status_code, status.HTTP_429_TOO_MANY_REQUESTS)
        self.assertIn("retry_after", second.data)

    @patch("apps.accounts.utils.send_mail")
    def test_resend_otp_rate_limit_is_bypassed_without_session_cookie(
        self, mocked_send_mail
    ):
        """
        Security-relevant test: proves the weakness flagged earlier.
        Using a fresh APIClient with no cookie jar simulates a client
        that never sends the session cookie back (e.g. a misconfigured
        CORS client, or an attacker deliberately dropping cookies).
        The cooldown must NOT apply in that case with the current
        implementation, because request.session is a brand-new,
        anonymous session on every request.

        This test is expected to keep passing until the rate limiting
        is moved to a user-keyed store (cache/DB) instead of the
        session. If you fix that, this test should be flipped to assert
        HTTP_429_TOO_MANY_REQUESTS instead.
        """
        from rest_framework.test import APIClient

        token = self._get_valid_token()

        stateless_client_1 = APIClient()
        stateless_client_2 = APIClient()

        first = stateless_client_1.post(
            self.resend_otp_url, {"verification_token": token}
        )
        second = stateless_client_2.post(
            self.resend_otp_url, {"verification_token": token}
        )

        self.assertEqual(first.status_code, status.HTTP_200_OK)
        self.assertEqual(second.status_code, status.HTTP_200_OK)

    def test_resend_otp_with_invalid_token_returns_401(self):
        response = self.client.post(
            self.resend_otp_url, {"verification_token": "garbage"}
        )
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)


class LoginFlowTests(AuthenticationE2ETestCase):
    """
    Covers steps 8-9: authenticating with valid credentials and
    confirming the returned session/user payload, plus the negative
    paths that guard against inactive-user login and bad credentials.
    """

    def setUp(self):
        super().setUp()
        self.register_user()
        self.user = User.objects.get(email=self.valid_payload["email"])

    def activate_user_through_real_flow(self):
        """
        Shared helper so login/logout/protected-endpoint tests don't
        re-implement the OTP dance. Still goes through the real
        endpoints -- it just wraps the sequence already proven correct
        by EmailVerificationFlowTests.
        """
        with patch("apps.accounts.utils.send_mail"):
            send_response = self.request_otp(self.user.email)
            token = send_response.data["verification_token"]
            otp_code = self.get_latest_otp_code(self.user)
            self.client.post(
                self.verify_otp_url,
                {"otp_code": otp_code, "verification_token": token},
            )
        self.user.refresh_from_db()

    def test_login_with_inactive_user_is_rejected(self):
        """
        Guards the invariant that OTP verification is a hard
        prerequisite for login, not just a UI-level suggestion.
        """
        response = self.client.post(
            self.login_url,
            {
                "email": self.valid_payload["email"],
                "password": self.valid_payload["password1"],
            },
        )

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertFalse(response.data["success"])

    def test_login_with_valid_credentials_succeeds_after_activation(self):
        self.activate_user_through_real_flow()

        response = self.client.post(
            self.login_url,
            {
                "email": self.valid_payload["email"],
                "password": self.valid_payload["password1"],
            },
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["success"])
        self.assertEqual(response.data["user"]["email"], self.user.email)
        self.assertIn("sessionid", response.cookies)

    def test_login_with_wrong_password_fails(self):
        self.activate_user_through_real_flow()

        response = self.client.post(
            self.login_url,
            {"email": self.valid_payload["email"], "password": "WrongPass123!"},
        )

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertFalse(response.data["success"])

    def test_login_error_message_does_not_distinguish_inactive_from_wrong_password(
        self,
    ):
        """
        Documents the user-enumeration weakness raised earlier: an
        inactive account currently returns 'Account is not activated'
        while a wrong password returns 'Invalid credentials'. This test
        is written to FAIL against the current code on purpose, making
        the vulnerability visible in CI rather than buried in a code
        review comment. Once LoginSerializer is fixed to return a
        single generic message for both cases, this test should pass.
        """
        self.activate_user_through_real_flow()

        wrong_password_response = self.client.post(
            self.login_url,
            {"email": self.valid_payload["email"], "password": "WrongPass123!"},
        )

        unknown_email_response = self.client.post(
            self.login_url,
            {"email": "nobody@example.com", "password": "WrongPass123!"},
        )

        self.assertEqual(
            wrong_password_response.data["message"],
            unknown_email_response.data["message"],
        )


class ProtectedEndpointAndLogoutFlowTests(AuthenticationE2ETestCase):
    """
    Covers steps 10-12: using an authenticated session against a
    protected endpoint, logging out, and confirming that logout actually
    invalidates the session.
    """

    def setUp(self):
        super().setUp()
        self.register_user()
        self.user = User.objects.get(email=self.valid_payload["email"])

        with patch("apps.accounts.utils.send_mail"):
            send_response = self.request_otp(self.user.email)
            token = send_response.data["verification_token"]
            otp_code = self.get_latest_otp_code(self.user)
            self.client.post(
                self.verify_otp_url,
                {"otp_code": otp_code, "verification_token": token},
            )

        self.client.post(
            self.login_url,
            {
                "email": self.valid_payload["email"],
                "password": self.valid_payload["password1"],
            },
        )

    def test_authenticated_user_can_access_protected_endpoint(self):
        """
        Uses the account overview endpoint (IsAuthenticated-protected,
        per profile_views wiring in urls.py) as the "protected resource"
        referenced in step 10. If that endpoint's permission class ever
        changes to AllowAny by mistake, this test fails loudly.
        """
        response = self.client.get(reverse("overview"))
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_logout_invalidates_session_for_protected_endpoint(self):
        """
        Step 12. After logout, the SAME client (same cookie jar) must
        no longer be able to reach a protected endpoint. This is the
        test that would catch a regression in auth_logout() wiring.
        """
        self.client.post(self.logout_url)

        response = self.client.get(reverse("overview"))
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_unauthenticated_logout_is_currently_not_rejected(self):
        """
        SECURITY-CRITICAL, currently failing by design.

        LogoutAPIView declares `premission_classes` (typo) instead of
        `permission_classes`. DRF silently ignores unrecognized
        attributes and falls back to the view's default permission
        classes, which -- unless overridden globally in settings --
        means AllowAny. This test proves an anonymous client can hit
        /logout/ and get a 200, when it should get 401/403.

        This test is intentionally written to assert the SECURE
        behavior (403), so it currently FAILS against the real code.
        Keep it failing/red until `premission_classes` is renamed to
        `permission_classes`; then it becomes a permanent regression
        guard.
        """
        anonymous_client = self.client_class()
        response = anonymous_client.post(self.logout_url)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
