# Generated by Django 5.2.13 on 2026-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_menu",
            field=models.BooleanField(default=True),
        ),
    ]
