# Generated by Django 4.2.30 on 2026-05-31 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_menuitem_is_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
