# Generated by Django 4.2.30 on 2026-07-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_restaurant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("drinks", "Drinks"),
                    ("main", "Main Meals"),
                    ("desserts", "Desserts"),
                    ("snacks", "Snacks"),
                    ("salads", "Salads"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
