# Generated by Django 4.2.30 on 2026-07-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[("verify", "Verify Email"), ("reset", "Reset Password")],
                max_length=20,
            ),
        ),
    ]
