
services:
  db:
    image: postgres:15-alpine
    container_name: fooddelivery-db
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]  # استخدم $$
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fooddelivery-network
    
  redis:
    image: redis:7-alpine
    container_name: fooddelivery-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fooddelivery-network
    
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fooddelivery-app  
    command: |
      sh -c "python manage.py collectstatic --noinput && \
        daphne -b 0.0.0.0 -p 8000 config.asgi:application "
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fooddelivery-network
    
  celery:
    build: .
    container_name: fooddelivery-celery
    command: celery -A config worker -l info -P solo -Q emails 
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy  
      db:
        condition: service_healthy  
    networks:
      - fooddelivery-network

  celery-beat:
    build: .
    container_name: fooddelivery-celery-beat
    command: celery -A config beat -l info  
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy  
    networks:
      - fooddelivery-network

  nginx:
    image: nginx:1.30-alpine
    container_name: fooddelivery-nginx
    env_file:
      - .env.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./templates/errors:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    
    depends_on:
      - web
    networks:
      - fooddelivery-network

volumes:
  postgres_data:
  media_files:

networks:
  fooddelivery-network:
    driver: bridge