# Generated by Django 5.2.13 on 2026-04-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="price_sapshot",
            new_name="price_snapshot",
        ),
    ]
